env:
  global:
    - secure: iRZ1iuFfPWuFSpJuyIr7ebYQ9/qowvBDKOvvdWbMW6jozo2PMy54XvoDE+6fgq+5+aYaIlYzYaEea2VzsAPEeMYTOPmpCQ2z8f/aotXNnRvpW/Q/8uwZRQgpCWeliY5CtleVvmPDWbYe2GnS0p8Q4vi7P7Vxfbgcizcb0v7iilGrNBnHxmkSpVcLmUefqOEBbqph8fZBaWxnfg8uE+hYhWnbl/XIybsFvmBKQ1J8XtnMKvlOBI7YWdQHyk2rTM5Bt/SOHRS0jHNW3vZfFqAzd9XvAfC+qVifo+I8ak05eT9sh5rqYDR04gOdssylMJmLxZDf0TD0uS9RgTW/FJZHk4gOSes/C0GO1Td0dq0fCRTYTMWljGv9CmwwiV6eCT6OUA7pOaPcN5HKFZdBeLBp9evfCJxrMfkanHXPnKhCQtzkRFnI41XOFoi9TvAKCKorIQLbhlY+xDVnUxjWnPYEcTlbX3cbYwdPtb94E6/Q3GT7bsmiSvVpCHRSgs5RxjKmTlFBAjDEiIwEgD4ZWWEvv+/nsvngpHwXGZCK9iEVzmsrsdimdRVCR196SepBh2H195nmA6s1GndHTc4bD6bLJ1JWtv009ZzJhFvlKG5tk1zHuhkam0Nb11JtLYEgRTfG8jiThyNN4MWsyVMrW8c2PfnbzyEBqpvvA3o4uy3PQ88=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
