env:
  global:
    - secure: DMRFqz4OvZ4xhXWLDDybveg0SEA4C11Az9crtevY5oCg0cGp8CS/Q1FLumwS1IseFpRPOK+taw4udgpXAdMt6Lsx0kVWX9tz47j+tAUO2sguosNgG5TlAg3Yt4eMoWTLzpVZsxqOdp4D6zOgQFC1TcX0kubYWz6jUDbFO4XasRHT+vykY3nEaWqKl5SWdLqgXMEDk8aBMsfQ1Hz5E3retIoEFWD93/er5nOMGqN+9D5YKPfrPxuqdM45BaPxY+cGEjaly/cEDRn6Or+wZG2VGQ0y4WjRhFi5073KFZFaWFzNU3E3QPFEdq0w7UHj/HyH9pTxBquW9onS3nY4aSFlJrDtyJKwbkvO4/aCRn2DuIZxT3BQC2m6zbrJmlJc28ljnH93B39eGqoKdpYo/S5TQ7POFFukWgCyMQAlScPCk/ZzODNLf6DsgSijfwykrwpqasiyX+dppv54iXWwtkQBQYEmiguZvKTnDvWk0fks0LKkCZI4vdodkmj447UQkAfW64qW37OrTOXjpG2p/2fgwA6Yk9wTcyOkixS2dduj2LMDIAXVnQFFi9od9Di52JUPoCLt8WtbaaQAmYpgk+WsLZbiqXfiipvWob9R0CVaGVPs280+KCK0yQ+qXNo+C+IrMDjBg+nTWDt4J3WwI6QMcqfR813TmA+VsMsfwpXNTGE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
