env:
  global:
    - secure: dGzDh5IITn4rmFlroqcuMQO8LU9a+xeS6zaU106WUeQzuH2nfkzZJKEy+pu/MbLQzHiq+oWqpH0HefzpDtOpcGnwkQbu6xD3AEaGd2F3kAjjdX9kzrktfNi7GEk4FLTrmg8FP6yt5AyiOPTq0S5IbcmVtszPLEN3W+nBFFZFg29XWoc5uXEhoXhRkT1pmyhMKlyxf8Vqi5BF5eR5OeMbxzIZuFpqDmcEz+P4IUnxHeBcadasm2AeiAsEuQ8p1RmldA4H2dGY//ZJQu2o/xrEm/m1ctI/KPi8U1lO7ZabyK6Yx53dJU5ilmtsRZk4y7D3vG0uWxC9Igq3y1ZfuHTfrbBGALW2rmfO70XEfTW0vHWxcNw56Q1HBUqMPxxGPtnPqabUL6L3eglRG5PHZJ7pm7ARX19s48z2WvBJC5tpCUmi/pLJA1pS6SjY/I0oPgmEKFOLHIbu1YFne9bXSZ9YBisWDrWk0ahqMPFVZtVTfkiTX7/KY+hA/7Z1g8NoG6EdWAusHKmsGBJwtOmybJYkdxWkpAHL6XD9xdvkEL00G+74tnSBCYKGqRa1vZItMJEfFxbrxYS+Ivjy54uybvD3PieaegepnDHMSofeHf6B5WhFPo0iZPlSKiJR0vGqeUjdSSfxdr5kVXbkeix81BAufspqhh09asjabIFq74aXinA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
