env:
  global:
    - secure: q+ScH888vuk6D6vRBoJBiYlekd70aFOAbvA8m2OZR5MikKL9UtjVNUq1EAz8cOte08n9E1M51QR7xpJ7sJLJgwQDRH9hQM1dIO7Ht3ilDLVmw/6x30DT1va+/2jzqpZfFlVLNzpprnMrwnOoYNgBT+qyYmfcouRWrDIPmoCIGmc+COo2sBQReuFuSBHAIaJ0/bQYCt52bg34i1JP7d5eNEvlEL8gxu2iKGcgUyrn8G0VHNf0xpgxFjdszqY5T/xrbMeFUIs0LcVy/RSjMigVXYDoANHePm+hJHrkVCUm2q/v5px8tarrFBj1uI1ztIHDBWnamnwOkoVeCB3qBFCTYQN0YN4iAVvFd7KoGQD/j6Ne8Hui9bcsdnTLN3hIFhECkn/oTo9oYXCzTYhfuNNQqwWI2HwtJBOt9KR5LK64pE5f7IpKMnta+g6bFAI+qcmrLXJCQNLcNVwGbe9nLMCu3lOM0uv+TKdTnqHtU2TR9ZCvhglHpk9IJQzw/JyxrXPNn03YDiduQku4NbshKRhQ/MD4T2Fg38HwrUyLlZ2gYLvAZiHTUAfPwR5jzNMd5AqnXmkco2oEryGQzFej5OoHkT8RHG734He9X/mr+BgqirZ0naqxWfK0AG4ZlGgwtnfeMA4jX6+Q34AZLSdcOyjfJZlIZkwTobsttJZphtRrc8E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
