env:
  global:
    - secure: NbvOxw830G+5CaYUKQypwHXTqzu8ydTIisu5Mubq2vb+m7IzPtN45D34IrVcLs7YpwG/7p0TrdXLA47FYIydsQF5E1KUBx/rax8+bURtTB9InJws/DAyfIdcO4J3nJ6n0vFZRIL07Xzv27ajLdz1XJcIulIybj8wFsV/QmQrKYAhVXBXbvD7BRNVNY0MsG4natxUx4VWv+ikvUyxMo6L0siY2jctSJ/Ncw7E90So6Na8bY7dY2Wo34i65B2Mw2ghlslmtCM+dgOc9hSz1/L/RjuP74G/1XCTzjnO3gcq3ox7xwBhLJnY+EmUSaamavk3Vth6uQCNwpSQZpu9osTY9QXMrgHhPqEmC/3dFWIow0y1iYfCcF+V8pLFwc1d7ZlFvC00HSshaXcwjPYVPuHmX8SUfCbwAeDe3Uf99PoxY/0L/atnLtG19pH973dfDl4EW+E84PHT6EYfAjkqntKxnPE6QrxcyVv25YA6BUFLUJY8+vDRFYf1zUyGBzH3u9E4cy9neWOF9dk1xUp3JyWXQmJ+By+yXCnSWv0vTDYBCHyAnRgspMXITWMufgYwVWNCTQn/Xtpf77EndYTKeJODdZT1oF1Qew8djH1kY9bUxZmIuBdVzAYd8eY+KuRrrIGlMTqIZ80xfhRc1gDUS2IOjipCHfHwkyB7jOhgxVy07/E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
