env:
  global:
    - secure: QVpqWd/XoAvv4oL0XA9Mu5iWRtzUAOSBmC8NJa1GmR8bjFGAjraH64RhqFcmIjNxeoupPvqXcpK+Ak7HyK22rTmziOU1pWmlkaFrb/ckE7wbUfuLa3l6Dd+TwxqvItZxpBY/AmZGVFg64HYJRM5vuG0bJORuBUuqOVXRtGAEm1+p3lwAnywwym7HAJn5fw0xACuYb0hOpzu5yZgPjeGXIH4BiIVyV5upvGhbAR5q0lChfJ180NClsHeVGeeZxczbh/WeYJ/RD4w9GyRZyaYxcSVPka5DuuRjnG8c75Xad5jwC0nwJ6Ik/rr3YTQXB6FRIW4qBwhtxkMIg7hekCuz4nuWaJ6lMB/ZOFSbpBaqz5epZ7aJj6cLpAWq5K4QO6F/5BpI9IXGXpx5DyAK1lN/hjHdI/XGrSxgzNuxI8GqDd1Adwgxz/AWYEfAMoqOf+YDbjt+y9vQ1cRf8Xd7UNhXKeUjlgbFfTrVzsRyrDteOxIVoH6WyiyWrJwk4AASuexYBghpYVRpfITNfTGZTEzgjfY4XxWLNFJaQr+vFhrCjsfM9aUnqMWDa3bGvRTzCAZLFnpjVY6X7YEquDUEevD6QkvCBdk87255Yb9F5JmxgrgXt+Lumz3eTN+csY2RFtL0ihq+TCDscw5x9f6uqo124LpxIyKssOX2+0UMytme4Ck=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
