env:
  global:
    - secure: ReW/Rkfax+1Oh7fmUvbm/VkniF4l+EaDu2IqNkbdJViBvN8LQE+JDVqrOhGMa0e/NMXyYFKXVQoIq8KEM3HXUEPBKwO92pCxG6bgCy1MR/+d8+mhmFkI414XpzuGZn1DSWyB9xRggOciOeZU96HM9m9w2r4rKZKQsVeq5QlQrRv51cHXbM8Ytpef1DnDf0rXtjnE1I6ad/FGTohswk2Wvu+ETnz4JupIbwvBB3YXxBeUFxpXgxFBWSgDSU0tLVo2qfYKyO13pURfYYWlrOZkP9XvTUUH6Kd4mCO+YigqcA5QdiZMhTaZYWipeOsyunbAcMrgS3rTXpJHDY3n2/MxbB8TqLMHRnUiuHXlijmZM/MWLm4AKd8pBqAq9AIp3ouOhFUrfzX9eMf2FeRyfEzQOnPKUUNFu94I+2OfGBMH9WWj8mA1CfJpEAVfE5J9kkkC7+d0YISGLzfIR2ebjtnPFGtUAjWannYJm/5fzfAeF8wrNm+B2ieiIy3C3/XvmJJ7rffyoXHzFJ2977WN+3JOAy2erRIAos8PvqoQnv6iKsH7vA+H/0K7Kka8utApLAXOSZm6rOur1erXEF+8/fCPxJEqGwpYAqXJKxZaLk2rtZl4/08IUoxsRWc2EyRiYg/lYJgS363h+RSbT0Z15gsYBBgpHSfmc7ShYmpGr0x/NRI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_tyzbit
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
